src/firstproject/firstproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

src/firstproject/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^top/?$', views.MostVotedView.as_view(), name='top'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^new/$', views.question_new, name='question_new'),
]

src/firstproject/polls/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
import datetime
from django.utils import timezone

# Models


@python_2_unicode_compatible  # only if you need to support Python 2
class Question(models.Model):
    question_text = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def get_votes(self):
        votes = 0
        for _choice in self.choice_set.all():
            votes += _choice.votes
        return votes

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


@python_2_unicode_compatible  # only if you need to support Python 2
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200, blank=False)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

src/firstproject/polls/forms.py
from django import forms
from django.forms import formset_factory

from .models import Question, Choice

# Forms


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_text',)


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('choice_text',)

    def __init__(self, *args, **kwargs):
        super(ChoiceForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

ChoiceFormSet = formset_factory(ChoiceForm, extra=3)

src/firstproject/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question
from .forms import QuestionForm, ChoiceForm, ChoiceFormSet

# Views


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class MostVotedView(generic.ListView):
    template_name = 'polls/top.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return sorted(Question.objects.all(), key=lambda x: -x.get_votes())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def question_new(request):
    if request.method == "POST":
        question_form = QuestionForm(request.POST)
        choices_form = ChoiceFormSet(request.POST)
        if question_form.is_valid():
            if choices_form.is_valid():
                question = question_form.save(commit=False)
                question.pub_date = timezone.now()
                question.save()
                for form in choices_form.forms:
                    choice = form.save(commit=False)
                    if not choice.choice_text:
                        continue
                    choice.question = question
                    choice.save()
                return HttpResponseRedirect(reverse('polls:index'))
    else:
        question_form = QuestionForm()
        choices_form = ChoiceFormSet()
    return render(request, 'polls/question_new.html', {'form': question_form, 'choices_form': choices_form})

src/firstproject/polls/templates/polls/_detail_modal.html
{% for question in latest_question_list %}
<!-- Modal -->
<div class="modal fade custom-modal-width" id={{ question.id }} tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Poll Detail</h4>
            </div>
            <div class="modal-body">
                {% include "./_results.html" %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}

src/firstproject/polls/templates/polls/_results.html
<div class="page-header">
    <h2>{{ question.question_text }}</h2>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Choice Text</th>
            <th>Votes</th>
        </tr>
    </thead>
    <tbody>
        {% for choice in question.choice_set.all %}
            <tr>
                <td>{{ choice.choice_text }}</td>
                <td>{{ choice.votes }} vote{{ choice.votes|pluralize }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

src/firstproject/polls/templates/polls/base.html
<!DOCTYPE html>
<html>
<head>
    <title>First Django Project</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'polls/favicon.ico' %}"/>
</head>

<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'polls:index' %}">Polls App</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Polls <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'polls:index' %}">View Recent</a></li>
                            <li><a href="{% url 'polls:top' %}">View Most Voted</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'polls:question_new' %}">Create</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="jumbotron container">
        <div>
            {% block body_block %}{% endblock %}
        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</body>
</html>

src/firstproject/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block body_block %}
    <div class="page-header">
        <h2>{{ question.question_text }}</h2>
    </div>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <div class="form-group">
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        </div>
    {% endfor %}
        <div class="form-group">
            <input class="btn btn-default" type="submit" value="Vote" />
        </div>
    </form>
{% endblock %}

src/firstproject/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block body_block %}
<div class="page-header">
    <h2>Recent Polls</h2>
</div>
{% if latest_question_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Question</th><th>Pub. Date</th><th>Actions </th>
            </tr>
        </thead>
        <tbody>
        {% for question in latest_question_list %}
            <tr>
                <td><a data-toggle="modal" data-target="#{{question.id}}">{{ question.question_text }}</a></td>
                <td>{{ question.pub_date }}</td>
                <td><a class="btn btn-xs btn-default" href="{% url 'polls:results' question.id %}">Results</a> | <a class="btn btn-xs btn-default" href="{% url 'polls:detail' question.id %}">Vote</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <small class="pull-right">Total: {{latest_question_list.count}}</small>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    {% include "./_detail_modal.html" %}
{% endblock %}

src/firstproject/polls/templates/polls/question_new.html
{% extends 'polls/base.html' %}
{% block body_block %}
<div class="page-header">
    <h2>New Poll</h2>
</div>

<form method="POST" class="form-group post-form">{% csrf_token %}
    {{ form.as_p }}
    <div class="divider"><hr></div>
    <div>You can leave empty choices.</div>
    <br>
    {{ choices_form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

src/firstproject/polls/templates/polls/results.html
{% extends 'polls/base.html' %}
{% block body_block %}
    {% include "./_results.html" %}

    <a href="{% url 'polls:detail' question.id %}" class="btn btn-default">Vote</a>
{% endblock %}

src/firstproject/polls/templates/polls/top.html
{% extends 'polls/base.html' %}
{% block body_block %}
    <div class="page-header">
        <h2>Top Polls</h2>
    </div>
    {% if latest_question_list %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Question</th><th>Votes</th><th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for question in latest_question_list %}
                <tr>
                    <td><a data-toggle="modal" data-target="#{{question.id}}">{{ question.question_text }}</a></td>
                    <td>{{ question.get_votes }}</td>
                    <td><a class="btn btn-xs btn-default" href="{% url 'polls:results' question.id %}">Results</a> | <a class="btn btn-xs btn-default" href="{% url 'polls:detail' question.id %}">Vote</a></td></tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    {% include "./_detail_modal.html" %}
{% endblock %}